apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: hello-bgis
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: default
---
apiVersion: v1
kind: Secret
metadata:
  name: bucket-creds
stringData:
  endpoint: minio.minio
  bucketName: hello-bgis
  accessKey: read-write-user
  secretKey: 'backstage@c2c'
